name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: 3.1.13
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.16
  firebase_core: 1.15.0
  firebase_storage: 10.2.14
  get: 4.6.1
  image_picker: ^0.8.5
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 8.2.1
  geocoding: 2.0.4
  syncfusion_flutter_datepicker: ^20.1.57
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
