// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCpFFWvjq0SbbyzCEHnvEDkt5FI9by38g',
    appId: '1:845718089385:android:252f7238a859f3162bc3b8',
    messagingSenderId: '845718089385',
    projectId: 'presence-ca834',
    storageBucket: 'presence-ca834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd2xRRkxcBnguh6sLB_X_rjMHS5zEqnY',
    appId: '1:845718089385:ios:eb5db645c641137f2bc3b8',
    messagingSenderId: '845718089385',
    projectId: 'presence-ca834',
    storageBucket: 'presence-ca834.appspot.com',
    iosClientId: '845718089385-kob6rbe7m2l94675t6afl5ubntkq0s98.apps.googleusercontent.com',
    iosBundleId: 'com.fredynur.presence',
  );
}
